-- Constants

-- Window
WINDOW_WIDTH = 400
WINDOW_HEIGHT = 800
WINDOW_WIDTH_HALF = WINDOW_WIDTH / 2
WINDOW_HEIGHT_HALF = WINDOW_HEIGHT / 2

-- Button
SMALL_BUTTON_WIDTH = 50
BUTTON_WIDTH = 150
BUTTON_HEIGHT = 50
MENU_BUTTON_X = WINDOW_WIDTH_HALF - (BUTTON_WIDTH / 2)

-- Ship
SHIP_INITIAL_Y = 700
SHIP_SPEED = 200

-- Bullet
BULLET_FIRE_DELAY = 0.1
BULLET_SPEED = 200

-- Enemy Formations
ENEMIES_PER_FORMATION = 5
ENEMY_FORMATION_ALL_HORIZONTAL = 'all-horizontal'
ENEMY_FORMATION_ALL_VERTICAL = 'all-vertical'

-- Enemies
ENEMY_INITIAL_Y = 100
ENEMY_SPEED = 100
ENEMY_SPAWN_DELAY = 0.5

-- Star
STAR_INITIAL_Y = -1
STAR_SPAWN_DELAY = 0.01
STAR_SPEED = 200